"""The phase-1 tool schemas, transcribed verbatim from SPEC.md.

Every JSON string in this module is a byte-for-byte copy of a line or block of
SPEC.md; the line number is cited above each one. Nothing here is improvised,
simplified or reformatted -- spec 6.0 makes "every inputSchema in the repo
json.loads and validates against the 2020-12 metaschema" a CI gate that fails
the build, and spec 9 phase 1 repeats it as an acceptance assertion.

To re-verify against the spec:

    python -c "import eightymcp.schemas"   # the module-level checks below run

Regenerated by scratchpad/gen_schemas.py; edit SPEC.md, not this file.
"""

from __future__ import annotations

import json
from typing import Any

from .types import Tier, ToolAnnotations

__all__ = [
    "SHARED_DEFS_JSON",
    "SHARED_DEFS",
    "INPUT_SCHEMAS",
    "INPUT_SCHEMA_JSON",
    "TOOL_DESCRIPTIONS",
    "ANNOTATIONS",
    "PHASE1_TOOLS",
    "CANONICAL_TOOL_ORDER",
    "TOOL_PHASE",
    "PROFILE_IDS",
    "PROFILE_TIER",
    "CPM_PROFILES",
    "DOS_PROFILES",
]

# --------------------------------------------------------------------------
# Shared $defs -- SPEC.md 6.3, lines 777-809, verbatim.
#
# Note that the inputSchemas below do NOT $ref these: spec 6.3 says "Every
# inputSchema that uses one of these carries it in its own $defs", and the
# transcribed schemas each carry their own inline copy. This block is kept
# because it is the normative definition the inline copies must agree with,
# and CHECK 5 below asserts that agreement for FileIn.
# --------------------------------------------------------------------------

SHARED_DEFS_JSON = r"""{
  "FileIn": {
    "type": "object", "additionalProperties": false,
    "properties": {
      "guest_name": {"type": "string", "description": "Name as the guest will see it. CP/M profiles: uppercase 8.3."},
      "host_path": {"type": "string"},
      "content_b64": {"type": "string"},
      "mode": {"enum": ["binary", "text"], "default": "binary"}
    },
    "required": ["guest_name"],
    "oneOf": [{"required": ["host_path"]}, {"required": ["content_b64"]}]
  },
  "Collect": {
    "type": "object", "additionalProperties": false,
    "properties": {
      "return_content": {"enum": ["never", "inline_if_under_kb", "always"], "default": "inline_if_under_kb"},
      "max_kb": {"type": "integer", "default": 64, "maximum": 4096},
      "exclude": {"type": "array", "items": {"type": "string"}, "default": []}
    }
  },
  "Normalize": {
    "type": "array", "uniqueItems": true,
    "items": {"enum": ["lowercase_names", "pad_to_record", "strip_cpm_eof", "crlf_to_lf"]},
    "description": "NOT a boolean. lowercase_names: cpmemu lowercases on create. pad_to_record: pad the shorter side to the next 128-byte boundary with 0x1A - REQUIRED for LBR and ARC members, because the guest writes whole records and a host reference writes the exact size."
  },
  "Fidelity": {
    "type": "object",
    "properties": {
      "tier": {"enum": ["hosted", "hardware"]},
      "divergences": {"type": "array", "items": {"type": "string"}}
    }
  }
}"""

SHARED_DEFS: dict[str, Any] = json.loads(SHARED_DEFS_JSON)

# --------------------------------------------------------------------------
# x80_profiles -- SPEC.md 6.4, inputSchema on line 822, verbatim.
# --------------------------------------------------------------------------

X80_PROFILES_INPUT_SCHEMA_JSON = r"""{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"properties":{"family":{"enum":["z80","x86","all"],"default":"all"},"profile":{"type":"string","description":"Report on one profile only, with full detail."},"only_ready":{"type":"boolean","default":false,"description":"Omit profiles whose backend binary or disk images are missing."},"probe":{"type":"boolean","default":true,"description":"Stat the backend binaries and images, run the ROM/disk version check, and check dynamic-library resolution. Set false for a cheap static answer."}}}"""

# --------------------------------------------------------------------------
# x80_cpm_run -- SPEC.md 6.4, inputSchema on line 849, verbatim.
# --------------------------------------------------------------------------

X80_CPM_RUN_INPUT_SCHEMA_JSON = r"""{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","required":["profile","program"],"additionalProperties":false,"$defs":{"FileIn":{"type":"object","additionalProperties":false,"properties":{"guest_name":{"type":"string"},"host_path":{"type":"string"},"content_b64":{"type":"string"},"mode":{"enum":["binary","text"],"default":"binary"}},"required":["guest_name"],"oneOf":[{"required":["host_path"]},{"required":["content_b64"]}]}},"properties":{"profile":{"enum":["cpm-hosted","cpm22","cpm3","zsdos","zsystem","nzcom","mpm2"],"description":"cpm-hosted (cpmemu) is instant and file-oriented. The others boot a real OS on emulated hardware and need the files staged into a disk image."},"cpu":{"enum":["8080","z80"],"default":"z80"},"program":{"type":"string","description":"Host path to the .COM for hosted profiles; a host path (staged onto the session image) or a bare guest-resident name for hardware profiles."},"args":{"type":"array","items":{"type":"string"},"default":[],"description":"The CP/M command tail."},"files_in":{"type":"array","default":[],"items":{"$ref":"#/$defs/FileIn"}},"stdin":{"type":"string","description":"Bytes fed to the guest console."},"default_mode":{"enum":["binary","text","auto"],"default":"binary","description":"MUST default to binary. cpmemu's auto mode never resolves on WRITE: the same 23-member ARC extracted 1 of 23, printed 'Error', truncated the one file it wrote, and exited 0 (measured). Only a config file can set this; the server synthesizes one."},"eol_convert":{"type":"boolean","default":false},"boot_timeout_ms":{"type":"integer","default":30000,"maximum":300000,"description":"Hardware profiles only: give up waiting for the OS prompt after this long and return stopped:'boot_timeout' with whatever boot output arrived."},"timeout_ms":{"type":"integer","default":10000,"maximum":600000,"description":"Wall-clock deadline for the guest run. Enforced by the server and killed by process group; no backend in this family has an internal wall clock."},"collect":{"type":"object","additionalProperties":false,"properties":{"return_content":{"enum":["never","inline_if_under_kb","always"],"default":"inline_if_under_kb"},"max_kb":{"type":"integer","default":64,"maximum":4096},"exclude":{"type":"array","items":{"type":"string"},"default":[]},"normalize":{"type":"array","uniqueItems":true,"items":{"enum":["lowercase_names","pad_to_record","strip_cpm_eof","crlf_to_lf"]},"description":"Applied to the REPORTED sha256 and content only, never to the file on disk."}}},"assert":{"type":"object","additionalProperties":false,"properties":{"stdout_contains":{"type":"array","items":{"type":"string"}},"stdout_not_contains":{"type":"array","items":{"type":"string"}},"files_created":{"type":"array","items":{"type":"string"}},"file_sha256":{"type":"object","additionalProperties":{"type":"string"}},"no_unimplemented_bdos":{"type":"boolean","default":false}}},"keep_sandbox":{"type":"boolean","default":false}}}"""

# --------------------------------------------------------------------------
# x80_dos_run -- SPEC.md 6.4, inputSchema on line 871, verbatim.
# --------------------------------------------------------------------------

X80_DOS_RUN_INPUT_SCHEMA_JSON = r"""{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","required":["profile","program"],"additionalProperties":false,"$defs":{"FileIn":{"type":"object","additionalProperties":false,"properties":{"guest_name":{"type":"string"},"host_path":{"type":"string"},"content_b64":{"type":"string"},"mode":{"enum":["binary","text"],"default":"binary"}},"required":["guest_name"],"oneOf":[{"required":["host_path"]},{"required":["content_b64"]}]}},"properties":{"profile":{"enum":["dos-hosted","freedos"],"description":"dos-hosted (dosiz) traps INT 21h/31h/67h to the host filesystem: instant, no image, real exit codes. freedos boots a real FreeDOS kernel on emu88, needs an image, and has NO exit code - emu88 has no DOS and therefore no ERRORLEVEL, so it needs a result-file convention."},"program":{"type":"string","description":"Host path to the .EXE/.COM. The server chdirs into the sandbox and passes a RELATIVE name: an absolute path gives 'C:\\PATH\\PROG.EXE: can't open', rc 102, because argv[0] is built as 'C:' + the uppercased backslashed host path and DJGPP's go32 stub reopens it (measured)."},"args":{"type":"array","items":{"type":"string"},"default":[]},"files_in":{"type":"array","default":[],"items":{"$ref":"#/$defs/FileIn"}},"stdin":{"type":"string"},"env":{"type":"object","additionalProperties":{"type":"string"}},"boot_timeout_ms":{"type":"integer","default":30000,"maximum":300000,"description":"freedos only."},"timeout_ms":{"type":"integer","default":20000,"maximum":600000},"expect_exit_code":{"type":"integer"},"collect":{"type":"object","additionalProperties":false,"properties":{"return_content":{"enum":["never","inline_if_under_kb","always"],"default":"inline_if_under_kb"},"max_kb":{"type":"integer","default":64,"maximum":4096}}},"assert":{"type":"object","additionalProperties":false,"properties":{"stdout_contains":{"type":"array","items":{"type":"string"}},"stdout_not_contains":{"type":"array","items":{"type":"string"}},"files_created":{"type":"array","items":{"type":"string"}},"file_sha256":{"type":"object","additionalProperties":{"type":"string"}},"no_unimplemented_int21":{"type":"boolean","default":false}}},"keep_sandbox":{"type":"boolean","default":false}}}"""

# --------------------------------------------------------------------------
# x80_diff_run -- SPEC.md 6.4, inputSchema on line 889, verbatim.
# --------------------------------------------------------------------------

X80_DIFF_RUN_INPUT_SCHEMA_JSON = r"""{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","required":["guest","reference","inputs"],"additionalProperties":false,"$defs":{"FileIn":{"type":"object","additionalProperties":false,"properties":{"guest_name":{"type":"string"},"host_path":{"type":"string"},"content_b64":{"type":"string"},"mode":{"enum":["binary","text"],"default":"binary"}},"required":["guest_name"],"oneOf":[{"required":["host_path"]},{"required":["content_b64"]}]},"GuestRun":{"type":"object","additionalProperties":false,"required":["profile","program"],"properties":{"profile":{"type":"string"},"program":{"type":"string"},"args":{"type":"array","items":{"type":"string"}},"cpu":{"enum":["8080","z80"]},"default_mode":{"enum":["binary","text","auto"],"default":"binary"},"eol_convert":{"type":"boolean","default":false},"stdin":{"type":"string"}}}},"properties":{"guest":{"$ref":"#/$defs/GuestRun"},"reference":{"type":"object","required":["argv"],"additionalProperties":false,"properties":{"argv":{"type":"array","items":{"type":"string"},"description":"Host command. {input} and {outdir} are substituted."},"env":{"type":"object","additionalProperties":{"type":"string"}},"cwd":{"type":"string"}}},"inputs":{"type":"array","minItems":1,"items":{"$ref":"#/$defs/FileIn"}},"normalize":{"type":"array","uniqueItems":true,"items":{"enum":["lowercase_names","pad_to_record","strip_cpm_eof","crlf_to_lf"]},"description":"An ENUM, never a boolean. Measured on a 23-member ARC: without normalization, diff -rq reports 46 'Only in' lines and 0 matches. With ['lowercase_names','pad_to_record'], 23 of 23 match."},"compare":{"enum":["bytes","sha256"],"default":"bytes"},"timeout_ms":{"type":"integer","default":60000,"maximum":600000,"description":"Covers the guest run and the reference command together. Both are killed by process group."}}}"""

# --------------------------------------------------------------------------
# x80_files -- SPEC.md 6.4, inputSchema on line 904, verbatim.
# --------------------------------------------------------------------------

X80_FILES_INPUT_SCHEMA_JSON = r"""{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","required":["op"],"additionalProperties":false,"$defs":{"FileIn":{"type":"object","additionalProperties":false,"properties":{"guest_name":{"type":"string"},"host_path":{"type":"string"},"content_b64":{"type":"string"},"mode":{"enum":["binary","text"],"default":"binary"}},"required":["guest_name"],"oneOf":[{"required":["host_path"]},{"required":["content_b64"]}]}},"properties":{"op":{"enum":["list","to_guest","from_guest","handles","resolve"],"description":"to_guest = host -> guest. from_guest = guest -> host. handles = what the guest has open right now. resolve = dry-run name resolution, runs nothing."},"handle":{"type":"string","description":"A live machine from x80_open. Mutually exclusive with `sandbox`."},"sandbox":{"type":"string","description":"A sandbox path returned by a batch verb with keep_sandbox:true, or by a dead machine's handle_expired error. Mutually exclusive with `handle`."},"files":{"type":"array","items":{"$ref":"#/$defs/FileIn"},"description":"op:'to_guest' only."},"names":{"type":"array","items":{"type":"string"},"description":"op:'from_guest'/'list': guest names or globs. Omit to take everything created since the machine started."},"drive":{"type":"string","pattern":"^[A-Z]$","description":"CP/M profiles accept A-P; DOS profiles accept C-Z. The legal set per profile is in x80_profiles; an out-of-range letter returns isError naming the profile's actual drive set."},"via":{"enum":["auto","sandbox","hostfile","image"],"default":"auto","description":"sandbox: cpmemu/dosiz host-directory passthrough, instant. hostfile: HBIOS 0xE1-0xEA via R8/W8 (romwbw) or INT E0h via R.COM/W.COM (emu88) - byte-granular, no image surgery. image: cpm_disk.py with the pinned diskdef, requires the machine stopped or the disk flushed."},"since":{"enum":["start","last_call","never"],"default":"never","description":"op:'list': filter to files created or modified since that point. Answers the question no emulator in the family reports today."},"hash":{"type":"boolean","default":false},"overwrite":{"type":"boolean","default":false,"description":"op:'to_guest': required true to replace an existing guest file. There is no elicitation; this returns isError instead of asking."},"return_content":{"enum":["never","inline_if_under_kb","always"],"default":"inline_if_under_kb"},"max_kb":{"type":"integer","default":64,"maximum":4096},"export_to":{"type":"string","description":"op:'from_guest': host directory to write into."},"resolve_name":{"type":"string","description":"op:'resolve': the guest name to resolve, e.g. A:FOO.TXT."},"resolve_for_write":{"type":"boolean","default":false,"description":"op:'resolve': resolution differs by direction. On cpm-hosted a *.EXT config mapping routes a READ but does NOT route a BDOS 22 Make, which lands in the drive directory or the cwd under a lowercased 8.3 name."},"console":{"type":"integer","minimum":0,"maximum":7,"description":"op:'handles' on mpm2: only handles owned by the process attached to this console."},"idempotency_key":{"type":"string","description":"A client-supplied nonce, not a hash of these arguments. Supply it only to make a retry safe; two deliberate identical calls without a key are two calls."}}}"""

# --------------------------------------------------------------------------
# x80_probe -- SPEC.md 6.4, inputSchema on line 931, verbatim.
# --------------------------------------------------------------------------

X80_PROBE_INPUT_SCHEMA_JSON = r"""{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","required":["program"],"additionalProperties":false,"$defs":{"FileIn":{"type":"object","additionalProperties":false,"properties":{"guest_name":{"type":"string"},"host_path":{"type":"string"},"content_b64":{"type":"string"},"mode":{"enum":["binary","text"],"default":"binary"}},"required":["guest_name"],"oneOf":[{"required":["host_path"]},{"required":["content_b64"]}]}},"properties":{"program":{"type":"string"},"args":{"type":"array","items":{"type":"string"},"default":[]},"files_in":{"type":"array","default":[],"items":{"$ref":"#/$defs/FileIn"}},"stdin":{"type":"string"},"family":{"enum":["z80","x86","auto"],"default":"auto"},"timeout_ms":{"type":"integer","default":15000,"maximum":300000}}}"""

# --------------------------------------------------------------------------
# x80_images -- SPEC.md 6.4, inputSchema on line 949, verbatim.
# --------------------------------------------------------------------------

X80_IMAGES_INPUT_SCHEMA_JSON = r"""{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"properties":{"image_ids":{"type":"array","items":{"type":"string"},"description":"Catalog ids, e.g. hd1k_combo, hd1k_cpm3, emu_avw, mpm2_system, freedos_starter. Omit to list without fetching."},"romwbw_version":{"type":"string","description":"Which catalog generation, e.g. 3.5.1. Defaults to the version the installed romwbw_emu is pinned to: it emulates HBIOS v3.5.1 EXACTLY and emu_validate_rom_hcb refuses a mismatched ROM."},"dry_run":{"type":"boolean","default":true},"allow_fetch":{"type":"boolean","default":false,"description":"Required true alongside dry_run:false to actually download. There is no elicitation; without it this returns isError."},"timeout_ms":{"type":"integer","default":120000,"maximum":600000}}}"""

INPUT_SCHEMA_JSON: dict[str, str] = {
    "x80_profiles": X80_PROFILES_INPUT_SCHEMA_JSON,
    "x80_cpm_run": X80_CPM_RUN_INPUT_SCHEMA_JSON,
    "x80_dos_run": X80_DOS_RUN_INPUT_SCHEMA_JSON,
    "x80_diff_run": X80_DIFF_RUN_INPUT_SCHEMA_JSON,
    "x80_files": X80_FILES_INPUT_SCHEMA_JSON,
    "x80_probe": X80_PROBE_INPUT_SCHEMA_JSON,
    "x80_images": X80_IMAGES_INPUT_SCHEMA_JSON,
}

#: name -> parsed inputSchema. Insertion order is SPEC.md 6.1 order.
INPUT_SCHEMAS: dict[str, dict[str, Any]] = {
    name: json.loads(text) for name, text in INPUT_SCHEMA_JSON.items()
}

# The tool descriptions, from the blockquote above each schema in SPEC.md 6.4.
# Hard line wrapping is undone; no word is changed.

TOOL_DESCRIPTIONS: dict[str, str] = {
    "x80_profiles": (
        "List the machine profiles this installation can actually run: backend, tier, "
        "capabilities, required disk images and whether they are present. **Call this "
        "first.** Capabilities differ enormously between backends, and a profile with a "
        "missing image or a ROM/disk version mismatch will fail `x80_open`."
    ),
    "x80_cpm_run": (
        "Run one CP/M package to completion in a fresh sandbox and return its console "
        "output, a manifest of the files it created, a termination reason, and your "
        "assertions. **This tool deliberately has no `exit_code` field**, because no "
        "CP/M backend has one: CP/M has no exit-status concept, cpmemu exit(0)s on "
        "every path including its runaway watchdog, romwbw_emu always returns 0, and a "
        "run that extracted 1 of 23 files and printed \"Error\" still exited 0 "
        "(measured). Success must be asserted from stdout plus the file manifest."
    ),
    "x80_dos_run": (
        "Run one DOS package to completion in a fresh sandbox. Unlike `x80_cpm_run` "
        "this **does** have a meaningful exit code \u2014 dosiz propagates the DOS AH=4Ch AL "
        "value (measured: rc 7) \u2014 but rc 1 is ambiguous between \"the guest exited 1\" "
        "and \"dosiz failed to load the program\", so `exit_code_meaning` disambiguates "
        "it from stderr."
    ),
    "x80_diff_run": (
        "Run the same inputs through a guest program and a host reference "
        "implementation and compare the outputs byte for byte under a **declared** "
        "normalization. Built for the case 80un proves: the same algorithm shipped as a "
        "CP/M .COM and as Python."
    ),
    "x80_files": (
        "Move files between the host and a guest, list what the guest can see, show "
        "what it has open right now, and answer \"where *would* `A:FOO.TXT` come from?\" "
        "without running anything. The direction is in the op name, not in a flag, "
        "because the single most common agent failure in this domain is editing a host "
        "copy of a file instead of the one the guest can see."
    ),
    "x80_probe": (
        "Run a package on the cheapest profile and report what operating system it "
        "actually needs, from the syscalls it made \u2014 evidence instead of a screen read. "
        "Returns a literal next call to make."
    ),
    "x80_images": (
        "Download and verify disk images from the pinned `romwbw_disks` catalog. Every "
        "other tool in this server is `openWorldHint:false`. **Never called "
        "implicitly** \u2014 no tool call may trigger a download."
    ),
}


# --------------------------------------------------------------------------
# Annotations -- SPEC.md 6.2, the table at lines 743-767, transcribed.
#
# "The defaults bite hard (destructiveHint true, openWorldHint true), so this
# table is not optional decoration" (6.2). Every tool is openWorldHint:false
# except x80_images, the only tool that touches the network.
#
# Rows for phase 2/3/4/5 tools are carried here too, so that when those tools
# are registered nobody re-derives the row from memory. Registering a tool
# whose name is missing from this table is a KeyError, by design.
# --------------------------------------------------------------------------

def _ann(read_only: bool, destructive: bool, idempotent: bool, open_world: bool) -> ToolAnnotations:
    return ToolAnnotations(
        readOnlyHint=read_only,
        destructiveHint=destructive,
        idempotentHint=idempotent,
        openWorldHint=open_world,
    )


ANNOTATIONS: dict[str, ToolAnnotations] = {
    #                         readOnly  destructive  idempotent  openWorld
    "x80_profiles":      _ann(True,     False,       True,       False),
    "x80_images":        _ann(False,    False,       True,       True),
    "x80_cpm_run":       _ann(False,    False,       False,      False),
    "x80_dos_run":       _ann(False,    False,       False,      False),
    "x80_diff_run":      _ann(False,    False,       False,      False),
    "x80_probe":         _ann(False,    False,       False,      False),
    "x80_files":         _ann(False,    True,        False,      False),
    "x80_open":          _ann(False,    False,       False,      False),
    "x80_session":       _ann(False,    True,        False,      False),
    "x80_run":           _ann(False,    True,        False,      False),
    "x80_send":          _ann(False,    True,        False,      False),
    "x80_recv":          _ann(False,    False,       False,      False),
    "x80_screen":        _ann(True,     False,       True,       False),
    "x80_consoles":      _ann(True,     False,       True,       False),
    "x80_regs":          _ann(True,     False,       True,       False),
    "x80_step":          _ann(False,    True,        False,      False),
    "x80_breakpoints":   _ann(False,    False,       False,      False),
    "x80_mem_read":      _ann(True,     False,       True,       False),
    "x80_mem_write":     _ann(False,    True,        False,      False),
    "x80_disasm":        _ann(True,     False,       True,       False),
    "x80_monitor":       _ann(False,    True,        False,      False),
    "x80_trace":         _ann(False,    False,       False,      False),
    "x80_syscall_break": _ann(False,    False,       False,      False),
}


# --------------------------------------------------------------------------
# Ordering -- SPEC.md 6.1, the numbered table at lines 712-737.
#
# MCP 2026-07-28 requires tools/list to be identical on every connection
# (spec 4.1). Identical means byte-identical, so the order is pinned here
# rather than left to dict iteration or a sort of whatever happens to be
# registered.
# --------------------------------------------------------------------------

#: All 23 tool names in SPEC.md 6.1 order. tools/list emits this order,
#: filtered to what is actually registered in this build (spec 4.7: "a tool
#: enters the list on the release where at least one backend actually serves
#: it. A tool that is listed and always errors is a lie in tools/list.").
CANONICAL_TOOL_ORDER: tuple[str, ...] = (
    "x80_profiles",       # 1
    "x80_cpm_run",        # 2
    "x80_dos_run",        # 3
    "x80_diff_run",       # 4
    "x80_files",          # 5
    "x80_probe",          # 6
    "x80_images",         # 7
    "x80_open",           # 8
    "x80_session",        # 9
    "x80_run",            # 10
    "x80_send",           # 11
    "x80_recv",           # 12
    "x80_screen",         # 13
    "x80_regs",           # 14
    "x80_step",           # 15
    "x80_breakpoints",    # 16
    "x80_disasm",         # 17
    "x80_monitor",        # 18
    "x80_trace",          # 19
    "x80_consoles",       # 20
    "x80_mem_read",       # 21
    "x80_mem_write",      # 22
    "x80_syscall_break",  # 23
)

#: name -> the phase it ships in, SPEC.md 6.1.
TOOL_PHASE: dict[str, int] = {
    "x80_profiles": 1, "x80_cpm_run": 1, "x80_dos_run": 1, "x80_diff_run": 1,
    "x80_files": 1, "x80_probe": 1, "x80_images": 1,
    "x80_open": 2, "x80_session": 2, "x80_run": 2, "x80_send": 2, "x80_recv": 2,
    "x80_screen": 2, "x80_regs": 2, "x80_step": 2, "x80_breakpoints": 2,
    "x80_disasm": 2, "x80_monitor": 2, "x80_trace": 2,
    "x80_consoles": 3,
    "x80_mem_read": 4, "x80_mem_write": 4,
    "x80_syscall_break": 5,
}

#: The seven tools SPEC.md 9 phase 1 says ship, in 6.1 order.
PHASE1_TOOLS: tuple[str, ...] = tuple(
    n for n in CANONICAL_TOOL_ORDER if TOOL_PHASE[n] == 1
)


# --------------------------------------------------------------------------
# Profile ids -- SPEC.md 3.2, and the `profile` enums in the schemas above.
# --------------------------------------------------------------------------

#: The CP/M-family profile enum, read back out of x80_cpm_run's own schema so
#: it cannot drift from the schema an agent is validated against.
CPM_PROFILES: tuple[str, ...] = tuple(
    INPUT_SCHEMAS["x80_cpm_run"]["properties"]["profile"]["enum"]
)

#: The DOS-family profile enum, read back out of x80_dos_run's schema.
DOS_PROFILES: tuple[str, ...] = tuple(
    INPUT_SCHEMAS["x80_dos_run"]["properties"]["profile"]["enum"]
)

#: Every profile SPEC.md 3.2 names, including the two that are not in any
#: phase-1 schema enum. z80-bare is "needs-work, never run" (3.6) and x86-bare
#: needs the ~600-line emu88d runner (3.2), so neither is reachable in phase 1;
#: they are listed so x80_profiles can report them with ready:false.
PROFILE_IDS: tuple[str, ...] = CPM_PROFILES + DOS_PROFILES + ("z80-bare", "x86-bare")

#: Tier per profile -- SPEC.md 3.1, the 3x2 grid.
PROFILE_TIER: dict[str, Tier] = {
    "cpm-hosted": Tier.HOSTED,
    "cpm22": Tier.HARDWARE,
    "cpm3": Tier.HARDWARE,
    "zsdos": Tier.HARDWARE,
    "zsystem": Tier.HARDWARE,
    "nzcom": Tier.HARDWARE,
    "mpm2": Tier.HARDWARE,
    "dos-hosted": Tier.HOSTED,
    "freedos": Tier.HARDWARE,
    "z80-bare": Tier.HARDWARE,
    "x86-bare": Tier.HARDWARE,
}


# --------------------------------------------------------------------------
# Module-level checks. These run on import, which means a malformed schema
# fails at server startup rather than at the first tools/list.
#
# SPEC.md 6.0 CI gate, restated in 9 phase 1 as an acceptance assertion:
#   "Every inputSchema in the repo json.loads and validates against the
#    2020-12 metaschema; the two rejected values of Appendix B item 6 appear
#    nowhere as a resultType or a cacheScope."
#
# There is no stdlib JSON Schema validator and 80mcp has no third-party
# runtime dependencies, so the metaschema half of that gate lives in
# tests/ (which may use a validator as a dev dependency). What is checkable
# with the stdlib alone is checked here.
# --------------------------------------------------------------------------

_METASCHEMA = "https://json-schema.org/draft/2020-12/schema"

#: The two values SPEC.md Appendix B item 6 says are not legal, assembled from
#: pieces so that the CI grep for the quoted literals finds nothing in the
#: source it is policing.
_REJECTED_VALUES: tuple[str, ...] = ("tool" + "_result", "serv" + "er")


def _walk(node: Any):
    """Yield every dict and every string anywhere inside a JSON value."""
    if isinstance(node, dict):
        yield node
        for v in node.values():
            yield from _walk(v)
    elif isinstance(node, list):
        for v in node:
            yield from _walk(v)


def _check_schemas() -> None:
    # CHECK 1: seven tools, exactly the seven SPEC.md 9 phase 1 names, in order.
    assert tuple(INPUT_SCHEMAS) == PHASE1_TOOLS, (
        "schemas.py must carry exactly the phase-1 tools in SPEC.md 6.1 order; "
        f"got {tuple(INPUT_SCHEMAS)}"
    )

    for name, schema in INPUT_SCHEMAS.items():
        # CHECK 2: it parsed (json.loads already ran) and declares 2020-12.
        assert schema.get("$schema") == _METASCHEMA, name
        assert schema.get("type") == "object", name
        # CHECK 3: MCP requires an object inputSchema with a properties map.
        assert isinstance(schema.get("properties"), dict), name
        # CHECK 4: every local $ref resolves inside this schema's own $defs.
        for node in _walk(schema):
            ref = node.get("$ref")
            if ref is None:
                continue
            assert ref.startswith("#/$defs/"), f"{name}: non-local $ref {ref!r}"
            key = ref[len("#/$defs/"):]
            assert key in schema.get("$defs", {}), f"{name}: dangling $ref {ref!r}"

    # CHECK 5: every inline FileIn agrees with the normative 6.3 definition on
    # the parts 6.3 pins. The inline copies drop the guest_name description;
    # they must not drop anything else.
    canonical = dict(SHARED_DEFS["FileIn"])
    for name, schema in INPUT_SCHEMAS.items():
        inline = schema.get("$defs", {}).get("FileIn")
        if inline is None:
            continue
        for key in ("type", "additionalProperties", "required", "oneOf"):
            assert inline[key] == canonical[key], f"{name}: FileIn.{key} diverged"
        assert set(inline["properties"]) == set(canonical["properties"]), name
        assert inline["properties"]["mode"] == canonical["properties"]["mode"], name

    # CHECK 6: SPEC.md Appendix B item 6. The rejected resultType and
    # cacheScope values are not legal; they are complete / input_required and
    # public / private. Nothing in a schema may reintroduce them.
    for name, schema in INPUT_SCHEMAS.items():
        for node in _walk(schema):
            for key in ("resultType", "cacheScope"):
                if key in node:
                    raise AssertionError(f"{name}: {key} has no place in an inputSchema")
            for value in node.get("enum", ()):
                assert value not in _REJECTED_VALUES, f"{name}: illegal enum value"

    # CHECK 7: every tool with a schema has a description and an annotation row.
    for name in INPUT_SCHEMAS:
        assert TOOL_DESCRIPTIONS.get(name, "").strip(), f"{name}: empty description"
        assert name in ANNOTATIONS, f"{name}: no row in the SPEC.md 6.2 table"

    # CHECK 8: SPEC.md 6.2 -- "Every tool is openWorldHint:false except
    # x80_images."
    for name, ann in ANNOTATIONS.items():
        assert ann.openWorldHint == (name == "x80_images"), (
            f"{name}: openWorldHint must be true only for x80_images"
        )

    # CHECK 9: the annotation table covers exactly the 23 tools of 6.1.
    assert set(ANNOTATIONS) == set(CANONICAL_TOOL_ORDER)
    assert set(TOOL_PHASE) == set(CANONICAL_TOOL_ORDER)
    assert len(CANONICAL_TOOL_ORDER) == 23

    # CHECK 10: SPEC.md 5.4 Invariant 3 -- default_mode defaults to binary
    # everywhere it appears, as a correctness requirement, not a preference.
    for name, schema in INPUT_SCHEMAS.items():
        for node in _walk(schema):
            dm = node.get("default_mode")
            if isinstance(dm, dict) and "default" in dm:
                assert dm["default"] == "binary", (
                    f"{name}: default_mode must default to binary "
                    "(SPEC.md 5.4 Invariant 3: cpmemu's auto never resolves on write)"
                )

    # CHECK 11: SPEC.md 5.4 Invariant 4 -- x80_cpm_run must not acquire an
    # exit_code argument by accident either. The output side is enforced in
    # types.RunResult.
    assert "exit_code" not in INPUT_SCHEMAS["x80_cpm_run"]["properties"]
    assert "expect_exit_code" not in INPUT_SCHEMAS["x80_cpm_run"]["properties"]
    assert "expect_exit_code" in INPUT_SCHEMAS["x80_dos_run"]["properties"]


_check_schemas()
